#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get -y update
apt-get -y install haproxy

# Create the config file
cat <<EOT > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend www-http
    bind *:80
    reqadd X-Forwarded-Proto:\ http
    default_backend web-backend

backend web-backend
    balance roundrobin
    # IMPORTANT: Replace these with your specific Web-01 and Web-02 IPs
    server web-01 52.91.210.233:80 check
    server web-02 54.237.133.112:80 check
EOT

service haproxy restart
