#!/usr/bin/env bash
# Ensures that Nginx is running and listening on port 80

# Start nginx service if it's not already running
sudo service nginx start

# Ensure nginx is listening on port 80
sudo ss -tuln | grep ':80'

# Check if Nginx is running properly by requesting the homepage
curl -I http://localhost:80 | head -n 1
