#!/usr/bin/env bash
# The condition block below checks if the parameters are exactly 4

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Now variables are assigned arguments
pathToFile=$1
serverIp=$2
username=$3
sshKey=$4

#scp(secure copy) is used to transfer file
scp -i "$sshKey" -o StrictHostKeyChecking=no "$pathToFile" "$username@$serverIp:~/"

