#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Edit default config to use custom 404
sed -i '/server_name _;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart nginx to apply the changes
systemctl restart nginx
