#!/usr/bin/env bash
# Configure Nginx with 301 redirect and custom 404 page

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Add redirect block under server_name _; (same strategy used in 3-redirection)
sed -i "/server_name _;/a \
    location /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
    }" /etc/nginx/sites-available/default

# Add custom 404 page
sed -i "/server_name _;/a \
    error_page 404 /error_404.html;" /etc/nginx/sites-available/default

service nginx restart
